#!/bin/sh

# Set -e to exit if any command fails
set -e

echo "Generating env.js from environment variables..."

# Path to the output env.js file (public so it's available to the frontend)
ENV_JS_PATH=/app/public/env.js

# Create the env.js file
cat <<EOF > $ENV_JS_PATH
window.__ENV__ = {
  NODE_ENV: "${NODE_ENV}",
  NEXT_PUBLIC_AUTH_URL: "${NEXT_PUBLIC_AUTH_URL}",
  NEXT_PUBLIC_API_BASE_URL: "${NEXT_PUBLIC_API_BASE_URL}",
  NEXT_PUBLIC_MAIN_TENANT_KEY: "${NEXT_PUBLIC_MAIN_TENANT_KEY}",
  NEXT_PUBLIC_IBL_TEMPLATE_MENTOR: "${NEXT_PUBLIC_IBL_TEMPLATE_MENTOR}",
  NEXT_PUBLIC_IBL_ALLOW_FREE_TRIAL_BANNER: "${NEXT_PUBLIC_IBL_ALLOW_FREE_TRIAL_BANNER}",
  NEXT_PUBLIC_IBL_PLATFORM: "${NEXT_PUBLIC_IBL_PLATFORM}",
  NEXT_PUBLIC_IBL_ENABLE_SPECIAL_LOGO_WHEN_IFRAMED: "${NEXT_PUBLIC_IBL_ENABLE_SPECIAL_LOGO_WHEN_IFRAMED}",
  NEXT_PUBLIC_MENTOR_IFRAME_URL: "${NEXT_PUBLIC_MENTOR_IFRAME_URL}",
  NEXT_PUBLIC_BASE_WS_URL: "${NEXT_PUBLIC_BASE_WS_URL}",
  NEXT_PUBLIC_IBL_LIVE_KIT_SERVER_URL: "${NEXT_PUBLIC_IBL_LIVE_KIT_SERVER_URL}",
  NEXT_PUBLIC_MENTOR_URL: "${NEXT_PUBLIC_MENTOR_URL}",
  NEXT_PUBLIC_MENTOR_SETTINGS_DISCLAIMER: "${NEXT_PUBLIC_MENTOR_SETTINGS_DISCLAIMER}",
  NEXT_PUBLIC_IFRAME_FROM_OLD_MENTOR: "${NEXT_PUBLIC_IFRAME_FROM_OLD_MENTOR}",
  NEXT_PUBLIC_IBL_SENTRY_DSN: "${NEXT_PUBLIC_IBL_SENTRY_DSN}",
  NEXT_PUBLIC_HELP_CENTER_URL: "${NEXT_PUBLIC_HELP_CENTER_URL}",
  NEXT_PUBLIC_SUPPORT_EMAIL: "${NEXT_PUBLIC_SUPPORT_EMAIL}",
  NEXT_PUBLIC_ENABLE_GRAVATAR_ON_PROFILE_PIC: "${NEXT_PUBLIC_ENABLE_GRAVATAR_ON_PROFILE_PIC}",
  NEXT_PUBLIC_DEFAULT_EMBED_CSS_URL: "${NEXT_PUBLIC_DEFAULT_EMBED_CSS_URL}",
  NEXT_PUBLIC_APP_BANNER_LINK: "${NEXT_PUBLIC_APP_BANNER_LINK}",
  NEXT_PUBLIC_APP_BANNER_LINK_TEXT: "${NEXT_PUBLIC_APP_BANNER_LINK_TEXT}",
  NEXT_PUBLIC_APP_BANNER_BADGE: "${NEXT_PUBLIC_APP_BANNER_BADGE}",
  NEXT_PUBLIC_APP_BANNER_TEXT: "${NEXT_PUBLIC_APP_BANNER_TEXT}",
  NEXT_PUBLIC_SHOW_APP_BANNER: "${NEXT_PUBLIC_SHOW_APP_BANNER}",
  NEXT_PUBLIC_MENTOR_TRAINING_MAXIMUM_FILE_SIZE: "${NEXT_PUBLIC_MENTOR_TRAINING_MAXIMUM_FILE_SIZE}",
  NEXT_PUBLIC_HIDE_ANALYTICS: "${NEXT_PUBLIC_HIDE_ANALYTICS}",
  NEXT_PUBLIC_SHOW_BASE_MENTOR: "${NEXT_PUBLIC_SHOW_BASE_MENTOR}",
  NEXT_PUBLIC_STRIPE_ENABLED: "${NEXT_PUBLIC_STRIPE_ENABLED}",
  NEXT_PUBLIC_DISABLED_DATASETS: "${NEXT_PUBLIC_DISABLED_DATASETS}",
  NEXT_PUBLIC_DISABLED_ANALYTICS_REPORTS: "${NEXT_PUBLIC_DISABLED_ANALYTICS_REPORTS}",
  NEXT_PUBLIC_ENABLE_ADVERTISING: "${NEXT_PUBLIC_ENABLE_ADVERTISING}",
  NEXT_PUBLIC_ENABLE_RBAC: "${NEXT_PUBLIC_ENABLE_RBAC}",
  NEXT_PUBLIC_PLATFORM_BASE_DOMAIN: "${NEXT_PUBLIC_PLATFORM_BASE_DOMAIN}",
};
EOF

echo "env.js generated at $ENV_JS_PATH"

# Now start the Next.js app (adjust if you're using custom start scripts)
exec "$@"