export const SUBSCRIPTION_TRIGGERS = {
  PRICING_MODAL: "TRIGGER_PRICING_MODAL",
  SUBSCRIBE_USER: "TRIGGER_SUBSCRIBE_USER",
};

export const SUBSCRIPTION_USER_CAPABILITIES =  {
  FREE_TRIAL: "FREE_TRIAL",
  FREE_PACKAGE: "FREE_PACKAGE",
  STUDENT_UNDER_PAID_PACKAGE: "STUDENT_UNDER_PAID_PACKAGE",
  PAID_PACKAGE: "PAID_PACKAGE",
  PRO_PACKAGE: "PRO_PACKAGE",
  STARTER_PACKAGE: "STARTER_PACKAGE",
};