#!/bin/bash
# Instructions for checking what AASA file iOS cached

set -e

echo "==========================================="
echo "How to Check Cached AASA on iPhone"
echo "==========================================="
echo ""

echo "Current AASA file on server:"
echo ""
SERVER_SIZE=$(curl -s https://mentorai.iblai.app/.well-known/apple-app-site-association | wc -c | tr -d ' ')
echo "File size: $SERVER_SIZE bytes"
echo ""
curl -s https://mentorai.iblai.app/.well-known/apple-app-site-association | python3 -m json.tool
echo ""

echo "==========================================="
echo "Method 1: Check via Console.app (Mac)"
echo "==========================================="
echo ""
echo "1. Connect your iPhone to your Mac via cable"
echo ""
echo "2. Open Console.app (/Applications/Utilities/Console.app)"
echo ""
echo "3. Select your iPhone in the left sidebar"
echo ""
echo "4. In the search box, type: swcd"
echo ""
echo "5. Click 'Start' to begin streaming logs"
echo ""
echo "6. Look for recent messages containing:"
echo "   • 'AASA' or 'apple-app-site-association'"
echo "   • 'mentorai.iblai.app'"
echo "   • 'response_bytes=XXX' (this shows the cached file size)"
echo ""
echo "7. Compare the cached size with server size ($SERVER_SIZE bytes)"
echo "   • If they match → iOS has the latest AASA"
echo "   • If different → iOS has an old cached version"
echo ""

echo "==========================================="
echo "Method 2: Force Re-Download and Monitor"
echo "==========================================="
echo ""
echo "You can force iOS to download fresh and watch it happen:"
echo ""
echo "1. In Console.app, start filtering for 'swcd'"
echo ""
echo "2. On your iPhone, delete the app completely"
echo ""
echo "3. Restart your iPhone"
echo ""
echo "4. In Console.app, click 'Start' to stream logs"
echo ""
echo "5. On your iPhone, reinstall from TestFlight"
echo ""
echo "6. Watch the Console for messages like:"
echo "   'Beginning data task AASA-...'"
echo "   'response_bytes=XXX'"
echo ""
echo "7. The response_bytes should show $SERVER_SIZE"
echo "   This confirms iOS downloaded the current version"
echo ""

echo "==========================================="
echo "Method 3: Test Individual Paths"
echo "==========================================="
echo ""
echo "Indirectly verify which paths iOS recognizes:"
echo ""
echo "In Notes app, test each path separately:"
echo ""
echo "Test these links one by one:"
echo "  ✓ https://mentorai.iblai.app/sso-login"
echo "  ? https://mentorai.iblai.app/mobile-sso-login"
echo "  ? https://mentorai.iblai.app/mobile/test"
echo "  ? https://mentorai.iblai.app/test/example"
echo ""
echo "If some work and others don't, iOS has an old AASA that's"
echo "missing the newer paths."
echo ""

echo "==========================================="
echo "What to Look For in Console Logs:"
echo "==========================================="
echo ""
echo "Look for this pattern in previous logs:"
echo ""
echo "  Beginning data task AASA-... { domain: mentorai.iblai.app }"
echo "  Task <...> received response, status 200"
echo "  Task <...> summary ... response_bytes=XXX"
echo ""
echo "The response_bytes value tells you the cached file size."
echo "Current server AASA is $SERVER_SIZE bytes."
echo ""
echo "From your earlier logs, you had: response_bytes=601"
echo "Current server AASA is: $SERVER_SIZE bytes"
echo ""
if [ "$SERVER_SIZE" = "601" ]; then
    echo "✓ Sizes match! iOS should have the latest AASA."
    echo "  The issue might be:"
    echo "  • Testing from wrong place (Safari address bar)"
    echo "  • Query parameters being stripped by iOS"
    echo "  • Need to wait longer for validation to complete"
else
    echo "✗ Size mismatch! iOS has an outdated AASA cached."
    echo "  Solution: Delete app, restart phone, reinstall from TestFlight"
fi
echo ""

echo "==========================================="
echo "For Jailbroken Devices Only:"
echo "==========================================="
echo ""
echo "If your device is jailbroken, you can directly view the cached AASA at:"
echo "/var/mobile/Library/Caches/com.apple.SharedWebCredentials/"
echo ""
echo "(This directory is not accessible on non-jailbroken devices)"
echo ""
