#!/bin/sh

sh scripts/fix-yalc.sh

echo "Running typecheck..."
pnpm typecheck

echo "Running lint..."
pnpm lint:check

echo "Running build..."
pnpm build

echo "Running unit tests..."
pnpm test

echo "Checking test coverage for changed files..."
bash ./scripts/check-test-coverage.sh
