name: Test Minimal

on:
  workflow_dispatch:
    inputs:
      stg-slot:
        description: 'Stg slot'
        required: false
        default: '1'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from stg${{ inputs.stg-slot }}"
